package practica4interfaz;

import jade.gui.GuiEvent;
import jade.gui.GuiAgent;

/**
 *
 * @author sergioaguilar
 */
public class VentanaChat extends javax.swing.JFrame {
    private GuiAgent owner;
    public final int SENT_TYPE = 0;
    /**
     * Creates new form VentanaChat
     */
    public VentanaChat(GuiAgent a) {
        initComponents();
        owner = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfResponder = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taReceived = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        taSent = new javax.swing.JTextField();
        enviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Agente Destino");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));
        getContentPane().add(tfResponder, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 160, -1));

        jLabel2.setText("Mensajes Recibidos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, 20));

        taReceived.setColumns(20);
        taReceived.setRows(5);
        jScrollPane1.setViewportView(taReceived);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 410, 100));

        jLabel3.setText("Mensaje a enviar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, -1));
        getContentPane().add(taSent, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 160, -1));

        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        getContentPane().add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        System.out.println("Mensaje del boton");
        
        GuiEvent ge = new GuiEvent(this, SENT_TYPE);
        ge.addParameter(tfResponder.getText());
        ge.addParameter(taSent.getText());
        owner.postGuiEvent(ge);
        taSent.setText("");
        
    }//GEN-LAST:event_enviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea taReceived;
    private javax.swing.JTextField taSent;
    private javax.swing.JTextField tfResponder;
    // End of variables declaration//GEN-END:variables
}
